= Button/Switch Input Module For Debugging

The purpose of this module is to be create push-button-initiated Wishbone transactions that can be used to make simple hardware tests of other wishbone devices.

This is not supposed to be a Wishbone GPIO peripheral, which would make more sense as a Wishbone device (which would receive read requests from external Wishbone controllers, or at most setting an interrupt line on change). This module is specifically designed to trigger new transactions, for use in testing other hardware components.

The module takes 4 buttons and 4 switches as input (mapping to the inputs on the Arty A7 board), and the output is the Wishbone controller interface, with the following signals (using Wishbone B4, pipelined-mode):

* `rst_i` (input): Synchronous active-high reset.
* `clk_i` (input): clock.
* `cyc_o` (output): Set while transaction in progress.
* `stb_o` (output): Set to initiate a new transaction.
* `we_o` (output): Set to indicate write, cleared for read (always set to 1 for this module).
* `dat_o` (output): Write-data to be sent to device. One byte, represents state of buttons/switches.
* `adr_o` (output): The address of the device to send data to.
* `ack_i` (input): Set by device to indicate transaction terminated with success.
* `err_i` (input): Set by device to indicate transaction terminated with failure.
* `rty_i` (input): Set by device to indicate transaction terminated and should be retried.
* `stall_i` (input): Set by device to indicate not yet ready to accept transaction.

The module synchronises and debounces the button/switch inputs, and then sends a Wishbone transaction each time the state of any of the inputs changes. The transactions are always writes, and the data is a single byte mapped as follows (using Arty A7 labels):

* Bit n, n < 4: `BTNn` is pushed
* Bit 4+n, n < 4: `SWn` is switched

== Button Debounce Timings

This section contains some basic measurements of the Arty A7 board to establish ballpark debounce timings. All measurements were made using A Rigol DS1054, between the pin on the button/switch and the ground on GPIO port JA. Measurements were made using a slow time base (1us/div) first to catch slow glitches, followed by a faster time base if required. Rise and fall times given below are measured from when the signal begins changing to approximately when the signal achieves its final steady state. Measurements were made with the board powered on.

Buttons display asymmetrical timing behaviour between rising and falling edges. On the rising edge (button press), transition times are very short, ranging from 50ns to 120ns. Fall times (button released) are roughly 1.5us.

The switches (side switches) have a much bigger issue with bouncing, especially when sliding the switch slowly. When sliding the switch quickly, the transition has normally settled within 10 ms. In the worst case scenario (sliding the switch slowly), bouncing can last for up to 200 ms).

By default, this module will assume a 100 MHz clock, and target a debounce period of 50ms, meaning the `DEBOUNCE_PERIOD` is `5_000_000`. Modify this number to trade-off input latency for risk of bouncing artefacts. Bouncing should only affect the switches, since the push buttons have no bouncing problems on this timescale.



