
####################################################################################
# Generated by Vivado 2023.2 built on 'Fri Oct 13 20:13:54 MDT 2023' by 'xbuild'
# Command Used: write_xdc -force -type io -type physical constraints.xdc
####################################################################################


# User Generated IO constraints 

set_property IOSTANDARD LVCMOS33 [get_ports {buttons[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green_leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds[0][blue]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds[0][green]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds[0][red]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds[1][blue]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds[1][green]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds[1][red]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds[2][blue]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds[2][green]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds[2][red]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds[3][blue]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds[3][green]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_leds[3][red]}]
set_property IOSTANDARD LVCMOS33 [get_ports rstn_i]

# User Generated physical constraints 

set_property PACKAGE_PIN C2 [get_ports rstn_i]
set_property PACKAGE_PIN E3 [get_ports clk_i]
set_property PACKAGE_PIN B8 [get_ports {buttons[3]}]
set_property PACKAGE_PIN B9 [get_ports {buttons[2]}]
set_property PACKAGE_PIN C9 [get_ports {buttons[1]}]
set_property PACKAGE_PIN D9 [get_ports {buttons[0]}]
set_property PACKAGE_PIN T10 [get_ports {green_leds[3]}]
set_property PACKAGE_PIN T9 [get_ports {green_leds[2]}]
set_property PACKAGE_PIN J5 [get_ports {green_leds[1]}]
set_property PACKAGE_PIN H5 [get_ports {green_leds[0]}]
set_property PACKAGE_PIN A10 [get_ports {switches[3]}]
set_property PACKAGE_PIN C10 [get_ports {switches[2]}]
set_property PACKAGE_PIN C11 [get_ports {switches[1]}]
set_property PACKAGE_PIN A8 [get_ports {switches[0]}]
set_property PACKAGE_PIN E1 [get_ports {rgb_leds[0][blue]}]
set_property PACKAGE_PIN F6 [get_ports {rgb_leds[0][green]}]
set_property PACKAGE_PIN G6 [get_ports {rgb_leds[0][red]}]
set_property PACKAGE_PIN G4 [get_ports {rgb_leds[1][blue]}]
set_property PACKAGE_PIN J4 [get_ports {rgb_leds[1][green]}]
set_property PACKAGE_PIN G3 [get_ports {rgb_leds[1][red]}]
set_property PACKAGE_PIN H4 [get_ports {rgb_leds[2][blue]}]
set_property PACKAGE_PIN J2 [get_ports {rgb_leds[2][green]}]
set_property PACKAGE_PIN J3 [get_ports {rgb_leds[2][red]}]
set_property PACKAGE_PIN K2 [get_ports {rgb_leds[3][blue]}]
set_property PACKAGE_PIN H6 [get_ports {rgb_leds[3][green]}]
set_property PACKAGE_PIN K1 [get_ports {rgb_leds[3][red]}]

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
